import type { Player } from '@/types/fighters'
import X from "@/assets/svg/x.svg";
import Instagram from "@/assets/svg/instagram.svg";
import Youtube from "@/assets/svg/youtube.svg";
import TikTok from "@/assets/svg/tiktok.svg";
import Twitch from "@/assets/svg/twitch.svg";
import Kick from "@/assets/svg/kick.svg";

export const PLAYERS: Player[] = [
  {
    id: 'alex',
    name: 'Álex',
    realName: 'Alejandro García López',
    age: 24,
    country: 'co',
    city: 'Barranquilla',
    neighborhood: 'El Prado',
    preferredFoot: 'Derecho',
    team: 'thunder',
    position: 'Delantero',
    number: 9,
    bio: 'Lleva jugando al fútbol desde los 5 años. Su ídolo es Messi y nunca pierde un partido en la playa.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/',
        label: 'Visitar perfil de Álex en Instagram',
        followers: '1.2k',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/',
        label: 'Visitar perfil de Álex en TikTok',
        followers: '3.4k',
        image: { logo: TikTok, width: 200, height: 200 },
      },
    ],
  },
  {
    id: 'laura',
    name: 'Laura',
    realName: 'Laura Martínez Ruiz',
    age: 22,
    country: 'co',
    city: 'Barranquilla',
    neighborhood: 'Centro Histórico',
    preferredFoot: 'Derecho',
    team: 'blaze',
    position: 'Centrocampista',
    number: 8,
    bio: 'Ex-jugadora de fútbol sala. Tiene un cañón en la pierna derecha y una visión de juego increíble.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/',
        label: 'Visitar perfil de Laura en Instagram',
        followers: '2.8k',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/',
        label: 'Visitar perfil de Laura en TikTok',
        followers: '5.1k',
        image: { logo: TikTok, width: 200, height: 200 },
      },
    ],
  },
  {
    id: 'carlos',
    name: 'Carlos',
    realName: 'Carlos Sánchez Pérez',
    age: 27,
    country: 'co',
    city: 'Barranquilla',
    neighborhood: 'Buenavista',
    preferredFoot: 'Zurdo',
    team: 'shadow',
    position: 'Defensa',
    number: 4,
    bio: 'Impenetrable en defensa. Nadie le gana un balón dividido. Juega con el corazón en la mano.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/',
        label: 'Visitar perfil de Carlos en Instagram',
        followers: '890',
        image: { logo: Instagram, width: 200, height: 200 },
      },
    ],
  },
  {
    id: 'maria',
    name: 'María',
    realName: 'María Fernanda Torres',
    age: 25,
    country: 'co',
    city: 'Barranquilla',
    neighborhood: 'Alto Prado',
    preferredFoot: 'Derecho',
    team: 'frost',
    position: 'Delantera',
    number: 11,
    bio: 'La velocidad es su superpoder. Llegó al torneo para demostrar que el fútbol femenino es imparable.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/',
        label: 'Visitar perfil de María en Instagram',
        followers: '4.2k',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/',
        label: 'Visitar perfil de María en TikTok',
        followers: '8.7k',
        image: { logo: TikTok, width: 200, height: 200 },
      },
    ],
  },
  {
    id: 'david',
    name: 'David',
    realName: 'David Gómez Hernández',
    age: 23,
    country: 'co',
    city: 'Barranquilla',
    neighborhood: 'Ciudad Jardín',
    preferredFoot: 'Derecho',
    team: 'iron',
    position: 'Portero',
    number: 1,
    bio: 'Bajo los tres palos no hay quien le supere. Se tira al barro como si fuera pan mojado en chocolate.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/',
        label: 'Visitar perfil de David en Instagram',
        followers: '650',
        image: { logo: Instagram, width: 200, height: 200 },
      },
    ],
  },
  {
    id: 'sofia',
    name: 'Sofía',
    realName: 'Sofía Ramírez Mendoza',
    age: 21,
    country: 'co',
    city: 'Barranquilla',
    neighborhood: 'Las Flores',
    preferredFoot: 'Zurdo',
    team: 'storm',
    position: 'Centrocampista',
    number: 10,
    bio: 'La maga del balón. Controla el ritmo del partido como nadie. Sueña con jugar en Europa.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/',
        label: 'Visitar perfil de Sofía en Instagram',
        followers: '3.1k',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'youtube',
        name: 'Youtube',
        url: 'https://www.youtube.com/',
        label: 'Visitar canal de Sofía en Youtube',
        followers: '1.2k',
        image: { logo: Youtube, width: 200, height: 200 },
      },
    ],
  },
  {
    id: 'pablo',
    name: 'Pablo',
    realName: 'Pablo Martín Díaz',
    age: 29,
    country: 'co',
    city: 'Barranquilla',
    neighborhood: 'Bellavista',
    preferredFoot: 'Derecho',
    team: 'night',
    position: 'Defensa',
    number: 5,
    bio: 'El capitán del equipo. Líder nato, organiza la defensa y nunca se rinde. Juega con sabiduría.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/',
        label: 'Visitar perfil de Pablo en Instagram',
        followers: '430',
        image: { logo: Instagram, width: 200, height: 200 },
      },
    ],
  },
  {
    id: 'ana',
    name: 'Ana',
    realName: 'Ana Belén Castro',
    age: 20,
    country: 'co',
    city: 'Barranquilla',
    neighborhood: 'Villa Carolina',
    preferredFoot: 'Derecho',
    team: 'golden',
    position: 'Delantera',
    number: 7,
    bio: 'Promesa del fútbol local. Tiene un regate endiablado y sonrisa fácil. Va a dar que hablar.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/',
        label: 'Visitar perfil de Ana en Instagram',
        followers: '6.3k',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/',
        label: 'Visitar perfil de Ana en TikTok',
        followers: '12k',
        image: { logo: TikTok, width: 200, height: 200 },
      },
    ],
  },
  {
    id: 'javier',
    name: 'Javier',
    realName: 'Javier Ruiz Moreno',
    age: 26,
    country: 'co',
    city: 'Barranquilla',
    neighborhood: 'Los Nogales',
    preferredFoot: 'Derecho',
    team: 'red',
    position: 'Centrocampista',
    number: 6,
    bio: 'Llegó al fútbol tarde, pero con talento sobra. Su pierna izquierda es un pincel. No para de correr.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/',
        label: 'Visitar perfil de Javier en Instagram',
        followers: '720',
        image: { logo: Instagram, width: 200, height: 200 },
      },
    ],
  },
  {
    id: 'elena',
    name: 'Elena',
    realName: 'Elena Vázquez García',
    age: 24,
    country: 'co',
    city: 'Barranquilla',
    neighborhood: 'San Marino',
    preferredFoot: 'Zurdo',
    team: 'dark',
    position: 'Defensa',
    number: 3,
    bio: 'Juega al fútbol desde que recuerda. Su padre fue entrenador y le enseñó todo. Técnica y garra.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/',
        label: 'Visitar perfil de Elena en Instagram',
        followers: '1.8k',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/',
        label: 'Visitar perfil de Elena en TikTok',
        followers: '2.3k',
        image: { logo: TikTok, width: 200, height: 200 },
      },
    ],
  },
  {
    id: 'miguel',
    name: 'Miguel',
    realName: 'Miguel Ángel Torres',
    age: 30,
    country: 'co',
    city: 'Barranquilla',
    neighborhood: 'El Golf',
    preferredFoot: 'Derecho',
    team: 'wild',
    position: 'Delantero',
    number: 14,
    bio: 'El más veterano del torneo. Experiencia y olfato de gol. Viene a demostrar que la edad es solo un número.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/',
        label: 'Visitar perfil de Miguel en Instagram',
        followers: '1.1k',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'x',
        name: 'X',
        url: 'https://x.com/',
        label: 'Visitar perfil de Miguel en X',
        followers: '510',
        image: { logo: X, width: 200, height: 200 },
      },
    ],
  },
  {
    id: 'claudia',
    name: 'Claudia',
    realName: 'Claudia Jiménez Ruiz',
    age: 19,
    country: 'co',
    city: 'Barranquilla',
    neighborhood: 'Paraíso',
    preferredFoot: 'Derecho',
    team: 'steel',
    position: 'Centrocampista',
    number: 16,
    bio: 'La más joven del torneo pero con una personalidad arrolladora. Juega con alegría y desparpajo.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/',
        label: 'Visitar perfil de Claudia en Instagram',
        followers: '5.6k',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/',
        label: 'Visitar perfil de Claudia en TikTok',
        followers: '15k',
        image: { logo: TikTok, width: 200, height: 200 },
      },
    ],
  },
  {
    id: 'sergio',
    name: 'Sergio',
    realName: 'Sergio Molina López',
    age: 28,
    country: 'co',
    city: 'Barranquilla',
    neighborhood: 'Riomar',
    preferredFoot: 'Derecho',
    team: 'thunder',
    position: 'Portero',
    number: 13,
    bio: 'Portero de fin de semana. Descubrió su talento bajo los palos en el instituto y nunca lo soltó.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/',
        label: 'Visitar perfil de Sergio en Instagram',
        followers: '340',
        image: { logo: Instagram, width: 200, height: 200 },
      },
    ],
  },
  {
    id: 'valeria',
    name: 'Valeria',
    realName: 'Valeria Ortiz Campos',
    age: 23,
    country: 'co',
    city: 'Barranquilla',
    neighborhood: 'Granadillo',
    preferredFoot: 'Zurdo',
    team: 'blaze',
    position: 'Delantera',
    number: 18,
    bio: 'Su velocidad y regate la hacen imparable en la banda. Llegó para dejar huella en el torneo.',
    socials: [
      {
        id: 'instagram',
        name: 'Instagram',
        url: 'https://www.instagram.com/',
        label: 'Visitar perfil de Valeria en Instagram',
        followers: '2.2k',
        image: { logo: Instagram, width: 200, height: 200 },
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        url: 'https://www.tiktok.com/',
        label: 'Visitar perfil de Valeria en TikTok',
        followers: '4.8k',
        image: { logo: TikTok, width: 200, height: 200 },
      },
    ],
  },
] as const
